---
# Per environment values which override defaults in prisoner-transactions/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-transactions-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://prisoner-transactions-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    PRISON_TRANSACTIONS_API_URL: "https://prisoner-transactions-api-dev.hmpps.service.justice.gov.uk"

  # Switches off the allow list in the DEV env only.
  allowlist: null

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

